name:                mapalgebra
version:             0.1.0
synopsis:            Efficient, polymorphic Map Algebra.
description:         Efficient, polymorphic Map Algebra.


                     This library is an implementation of /Map Algebra/ as described in the
                     book /GIS and Cartographic Modeling/ by Dana Tomlin. The fundamental
                     type, the `Raster`, is typesafe. Rasters of different size and projection
                     are considered different types, and so cannot be combined in any way.


                     Also featured are op fusion (i.e. "lazy Rasters"), extremely fast
                     Focal Operations, and typesafe NoData handling. Please see the
                     main module for a more detailed introduction.

homepage:            https://github.com/fosskers/mapalgebra
license:             BSD3
author:              Colin Woodbury
maintainer:          colin@fosskers.ca
copyright:           2018 Colin Woodbury
category:            Geography

extra-source-files:
  - README.md
  - data/*

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Wincomplete-uni-patterns
  # This introduces around a 2x speedup.
  # - -fllvm

dependencies:
  - base >= 4.9 && < 4.12
  - bytestring
  - containers
  - data-default
  - deepseq
  - massiv >= 0.1 && < 0.2
  - massiv-io >= 0.1 && < 0.2
  - hmatrix >= 0.18 && < 0.19
  - vector >= 0.11 && < 0.13

library:
  source-dirs: lib
  other-modules: []

tests:
  mapalgebra-test:
    main: Test.hs
    source-dirs: test
    other-modules: []
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - mapalgebra
      - HUnit-approx >= 1.1 && < 1.2
      - tasty >= 0.11 && < 2.0
      - tasty-hunit >= 0.9 && < 0.11
      - tasty-quickcheck >= 0.8 && < 0.10
      - QuickCheck

benchmarks:
  mapalgebra-bench:
    main: Bench.hs
    source-dirs: bench
    other-modules: []
    ghc-options:
      - -threaded
      - -O2
      - -with-rtsopts=-N
    dependencies:
      - criterion >= 1.1 && < 1.4
      - mapalgebra
